# Valid Suduku [every row and col sum = 45]

In [2]:
import numpy as np

In [40]:

arr = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9],
])

print(arr)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [35]:
# row sum
np.sum(arr, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
np.sum(arr, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])


### Hard way

In [43]:
# def validSuduku(arr):
#     rowSum = np.sum(arr, axis=1);
#     colSum = np.sum(arr, axis=0);

#     # every row and cols should be sum of 45
#     for x, y in zip(rowSum, colSum):
#         if x != 45 or y != 45:
#             return False

#     # aslo every 3x3 mat should be valid: every 3x3 should be sum of 45
#     v = np.vsplit(arr, 3)   #we got 3 virtical arrays each containing 3, 3*3
#     h1 = np.hsplit(v[0], 3)  # has 3, 3x3 mat
#     h2 = np.hsplit(v[1], 3)  # has 3, 3x3 mat
#     h3 = np.hsplit(v[2], 3)  # has 3, 3x3 mat

#     for x, y, z in zip(h1, h2, h3):
#         if np.sum(x) != 45 or np.sum(x) != 45 or np.sum(x) != 45:
#             return False
    
#     return True


In [44]:
# validSuduku(arr)

### Easy way

In [59]:
def validSuduku(arr):
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            a3x3seg = arr[i:i+3, j:j+3]
            if np.sum(a3x3seg) != 45:
                return False

    return True


validSuduku(arr)

True

## General Question

In [61]:
# col: age | MathMarks | sciMarks
# rows: students
data = np.array([
    [18, 85, 78], 
    [19, 92, 88], 
    [17, 67, 95], 
    [18, 65, 70], 
    [20, 90, 85]
])

In [62]:
# find the avg age of student 
np.mean(data[:, 0])   # all rows and 0th col

18.4

In [64]:
#Extract math marks of all the students 
data[:, 1]

array([85, 92, 67, 65, 90])

In [66]:
#find highes marks in sci
data[:, 2].max()

95

In [77]:
# students who scored > 90 in maths
mathMarks = data[:, 1]
mathBool = mathMarks > 90

#rollNo who got th hghest marks
data[:, 0][mathBool]

# data[:, 0][data[:, 1] > 90]

array([19])

### IMP

In [80]:
#inc the math marks by 2
data[:, 1] += 2
data

array([[ 18,  97,  78],
       [ 19, 104,  88],
       [ 17,  79,  95],
       [ 18,  77,  70],
       [ 20, 102,  85]])

In [83]:
# number of student younger than 19
len(data[data[:, 0] < 19])

3

In [86]:
# get the col wise mean of math of sci
np.mean(data[:, 1:], axis=0)

array([91.8, 83.2])

In [98]:
#get the data of students who scored atleast 80 in both subject
# NOTE: () and & is imp
# within numpy arra always use & as and    | for or
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[ 19, 104,  88],
       [ 20, 102,  85]])

In [99]:
data

array([[ 18,  97,  78],
       [ 19, 104,  88],
       [ 17,  79,  95],
       [ 18,  77,  70],
       [ 20, 102,  85]])

In [105]:
#replace all sci marks < 75 with 0
# data[:, 2][data[:, 2] < 75]
# we are selecting the col in which we wanna change and changing the value where there was true in boolean
data[:, 2][data[:, 2] < 75] = 0
data

array([[ 18,  97,  78],
       [ 19, 104,  88],
       [ 17,  79,  95],
       [ 18,  77,   0],
       [ 20, 102,  85]])