In [2]:
import numpy as np

In [4]:
arr = np.arange(11, 21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


### Slicing

In [5]:
arr[4]

15

In [8]:
arr[5:8]

array([16, 17, 18])

In [10]:
arr[:3]

array([11, 12, 13])

In [12]:
arr[7:]

array([18, 19, 20])

In [13]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

# slicing of matrix

In [15]:
mat = np.arange(1, 31).reshape(5, 6)
print(mat)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [17]:
mat[1]

array([ 7,  8,  9, 10, 11, 12])

In [21]:
mat[1, 2]   #as mat[1][2]

9

`mat[<rowSlice>, <colSlice>]`

In [23]:
mat[0:2, 1:4]    #slice row 0&1 and col 1to4

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [24]:
mat[2:, 3:]

array([[16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])

In [26]:
#col slice
mat[:, 3]

array([ 4, 10, 16, 22, 28])

### Boolean indexing

In [28]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
even_idx = arr % 2 == 0
print(even_idx)

[False  True False  True False  True False  True False  True]


In [35]:
arr[even_idx]

array([ 2,  4,  6,  8, 10])