In [1]:
import numpy as np

# Array Op


In [6]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30, 40])
print(arr1, arr2)

[1 2 3 4] [10 20 30 40]


In [8]:
arr1 + arr2

array([11, 22, 33, 44])

### note: always save the returned value to retain

In [9]:
arr1 - arr2

array([ -9, -18, -27, -36])

In [11]:
arr1/arr2

array([0.1, 0.1, 0.1, 0.1])

In [12]:
arr1 // arr2

array([0, 0, 0, 0])

### Broadcasting: is a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes

In [15]:
arr1 + 5

array([6, 7, 8, 9])

In [18]:
mat = np.arange(1, 13).reshape(3, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
#broadcating in mat
mat + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

### Deep and shalow copy

In [26]:
# slcie always create a deep copy for both ls and ndarray

ls = [1,2,3,4,5]
ls_copy = ls[:3]
for x in range(len(ls_copy)):
    ls_copy[x] *= 10

print(ls_copy)
print(ls)

[10, 20, 30]
[1, 2, 3, 4, 5]


In [30]:
# shallow copy
arr = np.arange(1, 4)
brr = arr
# brr = arr.copy()  #deep copy
brr[0] = 110000
arr

array([110000,      2,      3])

### matrix operations

In [35]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[3, 4], [3, 4]])

print(m1)
print(m2)

[[1 2]
 [3 4]]
[[3 4]
 [3 4]]


In [37]:
m1+m2

array([[4, 6],
       [6, 8]])

In [39]:
m1-m2

array([[-2, -2],
       [ 0,  0]])

In [41]:
#normal mul
m1 * m2

array([[ 3,  8],
       [ 9, 16]])

In [45]:
#actual mul - dot product
m1 @ m2
# np.dot(m1, m2)

array([[ 9, 12],
       [21, 28]])

In [46]:
# transepose

In [48]:
m1

array([[1, 2],
       [3, 4]])

In [50]:
m1.T

array([[1, 3],
       [2, 4]])

### Stacking vector   [Matrix are already stacked, not possible]

In [51]:
a1 = np.array([1, 2, 3])
a2 = np.array([10, 20, 30])

In [54]:
#vertical stack
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [56]:
# horizontal stack
np.hstack((a1, a2))

array([ 1,  2,  3, 10, 20, 30])

In [57]:
#colum stack

In [59]:
np.column_stack((a1, a2))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

### Spliting array in equal half

In [66]:
arr = np.arange(1, 17).reshape(4, 4)
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [68]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]